database:
  db: 
  user: 
  pass: 

pfsense:
    server: 
    client-id: 
    client-key: 

email:
    server: 
    address: 
    username: 
    password: 

backblaze:
    key-id: 
    auth-key: 

record_cache_dir: '/tmp'